### ISSUE TITLE
raw string literal testing disagrees with documentation

### ISSUE THREAD

**Issue by gibson042** [jmespath-community/jmespath.test#14]
jmespath.site [Grammar](https://jmespath.site/main/#spec-grammar) defines the grammar for raw string literals like

```abnf
raw-string        = "'" *raw-string-char "'" 
raw-string-char   = (%x20-26 / %x28-5B / %x5D-10FFFF) / preserved-escape / raw-string-escape 
preserved-escape  = escape (%x20-26 / %x28-5B / %x5D-10FFFF) 
raw-string-escape = escape ("'" / escape)
```
and [Raw String Literals](https://jmespath.site/main/#spec-raw-string-literals) includes a `search('\\', "") -> "\\"` example implying that `\\` is an escape sequence representing a single U+005C REVERSE SOLIDUS just like `\'` is an escape sequence representing a single U+0027 APOSTROPHE.

However, [tests/literal.json](https://github.com/jmespath-community/jmespath.test/blob/main/tests/literal.json) in this repository includes test cases contradicting the above, such as `{ "expression": "'\n'", "result": "\n" }` (a raw string literal including a U+000A LINE FEED, which is not covered by `raw-string-char`) and `{ "comment": "Backslash not followed by single quote is treated as any other character", "expression": "'\\\\'", "result": "\\\\" }` (added in 2016 by c0f7923dd1a091b209bd9b4247a89de7442b0a60).

Both disagreements ultimately affect whether or not raw string literals are capable of representing all possible sequences of code points (respectively those including C0 control characters and those including U+005C REVERSE SOLIDUS), and the latter is _especially_ odd—I've never heard of any other escaping approach in which the escape prefix itself is unrepresentable.

**Comment by springcomp** [comment]
While the example from the specification you are referring to is indeed incorrect, the spirit of the `raw-string` literal is basically to accept any character as is. It only processes the following two escape sequences:

- backslash followed by simple quote -> simple quote.
- backslash followed by itself -> backslash.

I think you have addressed this point in the [following pull-request](https://github.com/jmespath-community/jmespath.spec/pull/132).

However I do not see any conflicting examples in the [tests/literal.json](https://github.com/jmespath-community/jmespath.test/blob/aa6fb5f942e852af1781d1f208c4069a15794a80/tests/literal.json#L178-L197) you linked to.

May I suggest that you are incorrectly interpreting the example you are referring to which in facts, does not contain any backslash character at all, but indeed contains a linefeed? 🤔

|Expression|Expressed as JSON|Result|Comment
|---|---|---|---
`` '␊' `` | `` '\n' `` | `` "\n" `` | U+000A LINE FEED
`` '\u03a6' `` | `` '\\u03a6' `` | `` "\\u03a6" `` | Do not interpret escaped Unicode
`` 'foo\'bar' ``  | `` 'foo\\'bar' `` | `` "foo'bar" `` | Can escape the single quote
`` '\z' `` | `` '\\z' `` | `` "\\z" `` | Backslash not followed by single quote is treated as any other character",
`` '\\' `` | `` '\\\\' `` | `` "\\\\" `` |Backslash not followed by single quote is treated as any other character",

**Comment by gibson042** [comment]
> While the example from the specification you are referring to is indeed incorrect, the spirit of the `raw-string` literal is basically to accept any character as is. It only processes the following two escape sequences:
> 
> * backslash followed by simple quote -> simple quote.
> * backslash followed by itself -> backslash.

That makes sense to me, but the second bullet point is contradicted by the last test case at https://github.com/jmespath-community/jmespath.test/blob/aa6fb5f942e852af1781d1f208c4069a15794a80/tests/literal.json#L183-L197 . If backslash followed by backslash were an escape sequence representing a single backslash, then that case would instead look more like "Can escape the single quote":
```patch
         {
-          "comment": "Backslash not followed by single quote is treated as any other character",
+          "comment": "Can escape backslash",
           "expression": "'\\\\'",
-          "result": "\\\\"
+          "result": "\\"
         }
```

> May I suggest that you are incorrectly interpreting [the example you are referring to](https://github.com/jmespath-community/jmespath.test/blob/aa6fb5f942e852af1781d1f208c4069a15794a80/tests/literal.json#L154-L161) which in fact, does not contain any backslash character at all, but indeed contains a linefeed?

I don't think so, and I'll demonstrate using your table:

Expression | Expressed as JSON | Result | Comment | Response
-- | -- | -- | -- | --
`'␊'` | `'\n'` | `"\n"` | U+000A LINE FEED | _not currently allowed by [`raw-string-char = (%x20-26 / %x28-5B / %x5D-10FFFF) / preserved-escape / raw-string-escape`](https://jmespath.site/main/#spec-grammar)_
`'\u03a6'` | `'\\u03a6'` | `"\\u03a6"` | Do not interpret escaped Unicode | ✔
`'foo\'bar'` | `'foo\\'bar'` | `"foo'bar"` | Can escape the single quote | ✔
`'\z'` | `'\\z'` | `"\\z"` | Backslash not followed by single quote is treated as any other character | ✔
`'\\'` | `'\\\\'` | `"\\\\"` | Backslash not followed by single quote is treated as any other character | _JSON text `"\\\\"` expresses a string consisting of **two** consecutive backslashes rather than a string consisting of just a **single** backslash, so this result is analogous to the preceding `'\z'` ↔︀︁︎︎︎ ``` `"\\z"` ``` rather than to the `'\''` ↔️︎ ``` `"'"` ``` that I think we both consider preferable_

**Comment by springcomp** [comment]
I realize that control characters are not currently specified as valid for `raw-string` literals. Thanks for pointing this out. Indeed it seems we need to update the grammar rule accordingly.

Now I understand the last example as well. The JMESPath expression is a `raw-string` that contains two consecutive backslashes, which represents how a single backslash is escaped. Thus the resulting string should be a single backslash, which in JSON is represented by a sequence of two backslashes 🤔😏

I agree with your assessment.

**Comment by springcomp** [comment]
Or maybe just a subset of those supported as escape sequence in JSON:

```abnf
raw-string        = "'" *raw-string-char "'" 
raw-string-char   = (%x08-09 / %x0A / %x0C-0D / %x20-26 / %x28-5B / %x5D-10FFFF) / preserved-escape / raw-string-escape 
preserved-escape  = escape (%x08-09 / %x0A / %x0C-0D / %x20-26 / %x28-5B / %x5D-10FFFF) 
raw-string-escape = escape ("'" / escape)
```

**Comment by gibson042** [comment]
I would prefer to prohibit C0 control characters in raw strings, but if any are allowed then they all should be (and I don't know your comfort level with backwards-incompatible changes to the test suite, even if they are already supported by the formal grammar).

**Comment by springcomp** [comment]
I agree to forbid usage of control character in JMESPath expressions.
Seems that was never the intended spirit when [introduced in JEP-12](https://github.com/jmespath-community/jmespath.spec/blob/main/jep-012-raw-string-literals.md)

**Comment by springcomp** [comment]
This makes me realize that JEP-12 while having been accepted is actually incomplete. Thanks for pointing out all the subequent commits that collectives allude to the thought process at the time.

I think an addendum is required for JEP-12

**Comment by springcomp** [comment]
However, allowing ` \\ ` as a valid escape sequence *does* lend itself to the leaning toothpick syndrome that JEP-12 was explicitely trying to guard against… 🤔

**Comment by gibson042** [comment]
And in any case, this issue should probably be reopened.

**Comment by gibson042** [comment]
What would be the point of a `\'` escape to support representation of literal `'` without a corresponding `\\` escape to support literal representation of `\`? Your last example even presumes it:
> * `'preserving reverse \\ solidus'` ->  ` "preserving reverse \\ solidus"`

(_which in the absence of special treatment for `\\` like `raw-string-escape = escape ("'" / escape)` would instead have a result like `"preserving reverse \\\\ solidus"`_)

> That said, I’m not comfortable allowing C0 control characters in a `raw-string` as there would not be any easy way to write them in the first place…

Maybe not all of them, but remember that tab and line feed are included in that set. And it's also not too hard to get text containing ANSI escape sequences (which start with 0x1B).

**Comment by springcomp** [comment]
OK, I agree that the [current grammar](https://jmespath.org/specification.html#raw-string-literals) is consistent with the last example from that page:

```
search( '\\', "" ) -> "\\"
```

That example clearly illustrate usage of two consecutive backslash characters to escape a single resulting backslash character in the output string.

**Comment by springcomp** [comment]
> > That said, I’m not comfortable allowing C0 control characters in a `raw-string` as there would not be any easy way to write them in the first place…
> 
> Maybe not all of them, but remember that tab and line feed are included in that set. And it's also not too hard to get text containing ANSI escape sequences (which start with 0x1B).

To be clear, I’m explicitly referring to exanding the set of characters from `` %x20-26 `` to `` %x00-26 ``.
This is what I’m mostly uncomfortable with.

I can’t see a good use case for making an exception here in raw string and not in, say `quoting-string` expressions.

**Comment by gibson042** [comment]
> I can’t see a good use case for making an exception here in raw string and not in, say `quoting-string` expressions.

I can make that case: `quoted-string` is aligned with JSON and in particular already supports the representation of arbitrary code points by means of `\u` escapes, whereas `raw-string` supports escapes only for its delimiter and escape prefix and would otherwise be unable to represent code points from U+0000 through U+001F, limiting usability in a way that was rejected in [JEP-12 Alternative approaches](https://github.com/jmespath-community/jmespath.spec/blob/main/jep-012-raw-string-literals.md#disallow-single-quotes-in-a-raw-string) and (in the case of U+000A LINE FEED) explicitly _intended_ per [JEP-12 Examples](https://github.com/jmespath-community/jmespath.spec/blob/main/jep-012-raw-string-literals.md#examples).

**Comment by springcomp** [comment]
>  (in the case of U+000A LINE FEED) explicitly _intended_ per JEP-12 Examples.

I rest my case your honor 😏

**Comment by gibson042** [comment]
> I must admit that I do not understand the purpose of the `preserved-escape` rule🤔

I think I can explain it... the `raw-string-escape` rule exists as a place to attach the behavior by which a backslash escapes a following backslash or single quote, and backslash must therefore not be allowed in the parent `raw-string-char`. And given the (however misguided) desire to treat literally any backslash that is _not_ followed by one of those two characters, the `preserved-escape` rule is introduced to match and implement precisely that **lack** of escaping. Basically, the contents of a raw string are an arbitrarily long sequence in which each element is one of the following, collectively allowing representation of any code point sequence expressible in the outer encoding:
* the grouped alternatives of `raw-string-char`: any code point other than `'` or `\`, representing itself
* `raw-string-escape`: `\'` or `\\`, respectively representing `'` or `\`
* `preserved-escape`: `\` followed by a code point that is neither `'` or `\`, representing the sequence consisting of both code points in order

**Comment by springcomp** [comment]
I think this issue has been solved.
