### ISSUE TITLE
Unicode coverage is incomplete

### ISSUE THREAD

**Issue by gibson042** [jmespath-community/jmespath.test#2]
[unicode.json](https://github.com/jmespath-community/jmespath.test/blob/HEAD/tests/unicode.json) does not contain any supplementary plane code points (i.e., U+10000 through U+10FFFF). This is a rather large gap for a specification in which a string is a sequence of code points, and as a result there are unsurprising bugs in e.g. the [jmespath.js](https://github.com/jmespath/jmespath.js) implementation in use at [jmespath.site](https://jmespath.site/), which incorrectly treats each supplementary plane code point as if it were a sequence of two surrogate code points (_i.e., a code point from U+D800 through U+DBFF followed by a code point from U+DC00 through U+DFFF_):

| expression  | actual result | expected result |
| ------------- | ------------- | ------------- |
| `length('𝌆')` | `2` | `1`
| `reverse('a𝌆b')` | `"b\udf06\ud834a"` | `"b𝌆a"`
| `sort(['𝌆','北'])` | `[ "𝌆", "北" ]` | `[ "北", "𝌆" ]`

**Comment by springcomp** [comment]
You are absolutely right. 

A JSON character is indeed a sequence of Unicode code points. Supplementary plan code points have to be encoded using a sequence of two 4-digit hexadecimal characters.

You are right that most library implementations are broken 😞 as they do not handle surrogate pairs correctly.
