### ISSUE TITLE
Test coverage needed for `split('', '')`

### ISSUE THREAD

**Issue by gibson042** [jmespath-community/jmespath.test#6]
cf. https://github.com/jmespath-community/jmespath.spec/pull/118

**Comment by springcomp** [comment]
I think this is [already addressed](https://github.com/jmespath-community/jmespath.test/blob/4f0476875424d68ae5a13f674f010fd08af6a1e3/tests/string_functions.json#L134).

Did you have another corner case in mind?

**Comment by gibson042** [comment]
Nope, that looks good!
